# Generated by Django 2.1.3 on 2018-12-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timelapse', models.IntegerField(default=0)),
                ('argumentNumber', models.IntegerField()),
                ('correctness', models.BooleanField(default=False)),
                ('validity', models.BooleanField(default=False)),
                ('game_number', models.IntegerField(default=-1)),
            ],
        ),
    ]
