# Generated by Django 3.2.7 on 2021-09-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timelapse', models.IntegerField(default=0)),
                ('syllnumber', models.IntegerField()),
                ('figure', models.IntegerField()),
                ('correctness', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timelapse', models.IntegerField(default=0)),
                ('figure', models.IntegerField()),
                ('quantor_1', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('quantor_2', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('quantor_3', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('term_S', models.IntegerField(null=True)),
                ('term_M', models.IntegerField(null=True)),
                ('term_P', models.IntegerField(null=True)),
                ('correctness', models.BooleanField(default=False)),
                ('conclusion_truth_value', models.BooleanField(default=False)),
                ('student_answer', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=7)),
                ('propkind', models.CharField(choices=[('verbal', 'Verbal only'), ('graph', 'Verbal and CG')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Answer4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timelapse', models.IntegerField(default=0)),
                ('rule_clicks', models.IntegerField(default=0)),
                ('figure', models.IntegerField()),
                ('quantor_1', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('quantor_2', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('quantor_3', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('term_S', models.IntegerField(null=True)),
                ('term_M', models.IntegerField(null=True)),
                ('term_P', models.IntegerField(null=True)),
                ('correctness', models.BooleanField(default=False)),
                ('conclusion_truth_value', models.BooleanField(default=False)),
                ('student_answer', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=7)),
                ('propkind', models.CharField(choices=[('verbal', 'Verbal only'), ('graph', 'Verbal and CG')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Answer5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timelapse', models.IntegerField(default=0)),
                ('figure', models.IntegerField()),
                ('quantor_1', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('quantor_2', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('quantor_3', models.CharField(choices=[('au', 'All'), ('iu', 'Some'), ('eu', 'No'), ('ou', 'Some ... are not')], max_length=2)),
                ('term_S', models.IntegerField(null=True)),
                ('term_M', models.IntegerField(null=True)),
                ('term_P', models.IntegerField(null=True)),
                ('correctness', models.BooleanField(default=False)),
                ('conclusion_truth_value', models.BooleanField(default=False)),
                ('student_answer', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=7)),
                ('propkind', models.CharField(choices=[('verbal', 'Verbal only'), ('graph', 'Verbal and CG')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Answer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_truth_value', models.BooleanField(default=False)),
                ('term_S', models.IntegerField(null=True)),
                ('term_M', models.IntegerField(null=True)),
                ('term_P', models.IntegerField(null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logapp.answer')),
            ],
        ),
    ]
